version: '2'
 
services:
  mysql:
    image: mysql
    container_name: test-mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: "alvearroot"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - /storage/docker/mysql-datadir:/var/lib/mysql
